---
IMDB:
  _description_: "Describes IMDb content as from https://datasets.imdbws.com/"
  _legal_: "you must verify compliance with IMDb terms before any usage"
  _license_: "apache 2.0 license for this file https://www.apache.org/licenses/"
  _source_: "https://www.imdb.com/interfaces/ - accessed December 5th, 2019"
  comment: "tab-separated, UTF-8, headers in line 1, eol linefeed, \N for null"
  directory: ../data/imdb/
  download: "https://datasets.imdbws.com/"
  exclude_adult: true
  locale: de_ch
  fields:
    -
      column: attributes
      comment: "additional term(s) to describe alternative (not enumerated)"
      datatype: string
      format: "[^,]+(,[^,]+)*"
    -
      column: averageRating
      comment: "weighted average of all the individual user ratings"
      datatype: decimal
      format: \d\d?(\.|\.\d)?
    -
      column: birthYear
      comment: "year of birth"
      datatype: smallint
      format: "\\d{4}"
    -
      column: category
      comment: "category of a job"
      datatype: string
      format: ".{1,254}"
    -
      column: characters
      comment: "name(s) of character played (or null)"
      datatype: string
      format: .+
    -
      column: deathYear
      comment: "year of death, if applicable (or null)"
      datatype: smallint
      format: "\\d{4}"
    -
      column: directors
      comment: "director(s) of the title"
      datatype: string
      format: "nm\\d{7,8}(,nm\\d{7,8})*"
    -
      column: endYear
      comment: "TV Series end year. ‘\\N’ for all other title types"
      datatype: smallint
      format: "\\d{4}"
    -
      column: episodeNumber
      comment: "episode number in the TV series"
      datatype: mediumint
      format: "\\d{1,5}"
    -
      column: genres
      comment: "genres associated with the title"
      datatype: string
      format: "[^,]+(,[^,]+){0,2}"
    -
      column: isAdult
      comment: "boolean with values 0 non-adult title / 1 adult title"
      datatype: boolean
      format: (0|1)
    -
      column: isOriginalTitle
      comment: "boolean with values 0 not original title / 1 original title"
      datatype: boolean
      format: (0|1)
    -
      column: job
      comment: "job title (or null)"
      datatype: string
      format: ".{1,254}"
    -
      column: knownForTitles
      comment: "titles the person is known for"
      datatype: string
      format: "tt\\d{7,8}(,tt\\d{7,8})*"
    -
      column: language
      comment: "language of title"
      datatype: string
      format: ".{1,11}"
    -
      column: nconst
      comment: "alphanumeric unique identifier of the name/person"
      datatype: string
      format: "nm\\d{7,8}"
    -
      column: numVotes
      comment: "number of votes the title has received"
      datatype: string
      format: "\\d{1,10}"
    -
      column: ordering
      comment: "number to uniquely identify rows for a given titleId"
      datatype: tinyint
      format: "\\d{1,3}"
    -
      column: originalTitle
      comment: "original title, in the original language"
      datatype: string
      format: ".{1,254}"
    -
      column: parentTconst
      comment: "alphanumeric identifier of the parent TV Series"
      datatype: string
      format: "(tt|nm|co|ev|ch|ni)\\d{7,8}"
    -
      column: primaryName
      comment: "name by which the person is most often credited"
      datatype: string
      format: ".{1,254}"
    -
      column: primaryProfession
      comment: "top-3 professions of the person"
      datatype: string
      format: "[^,]+(,[^,]+){0,2}"
    -
      column: primaryTitle
      comment: "popular title, title used by filmmakers at point of release"
      datatype: string
      format: ".{1,254}"
    -
      column: region
      comment: "region for this version of title"
      datatype: string
      format: ".{1,10}"
    -
      column: runtimeMinutes
      comment: "primary runtime of title, in minutes"
      datatype: smallint
      format: "\\d{1,4}"
    -
      column: seasonNumber
      comment: "season number episode belongs to"
      datatype: smallint
      format: "\\d{1,4}"
    -
      column: startYear
      comment: "release year of title, start year for TV Series"
      datatype: smallint
      format: "\\d{4}"
    -
      column: tconst
      comment: "alphanumeric unique identifier of the title/episode"
      datatype: string
      format: "(tt|nm|co|ev|ch|ni)\\d{7,8}"
    -
      column: title
      comment: "localized title"
      datatype: string
      format: .+
    -
      column: titleId
      comment: "alphanumeric unique identifier of the title"
      datatype: string
      format: "tt\\d{7,8}"
    -
      column: titleType
      comment: "type/format of title, e.g. movie, short, tvseries, video, etc"
      datatype: string
      format: .+
    -
      column: types
      comment: "attributes of alternative, e.g. original, dvd, etc (enumerated)"
      datatype: string
      format: "[^,]+(,[^,]+)*"
    -
      column: writers
      comment: "writer(s) of the title"
      datatype: string
      format: "nm\\d{7,8}(,nm\\d{7,8})*"
  files:
    -
      comment: "rating and votes information for IMDb titles"
      filename: title.ratings.tsv.gz
      primary_key: tconst
      tablename: imdb_ratings
    -
      comment: "episode information for tv series"
      filename: title.episode.tsv.gz
      primary_key: tconst
      tablename: imdb_episodes
    -
      comment: "titles in internet movie database (IMDb)"
      filename: title.basics.tsv.gz
      primary_key: tconst
      tablename: imdb_titles
    -
      comment: "alternatives for IMDb titles (also know as - AKA)"
      filename: title.akas.tsv.gz
      primary_key: "tconst, ordering"
      tablename: imdb_alt_titles
    -
      comment: "director and writer information for all IMDb titles"
      filename: title.crew.tsv.gz
      primary_key: tconst
      tablename: imdb_crew
    -
      comment: "principal cast/crew for IMDb titles"
      filename: title.principals.tsv.gz
      primary_key: "tconst, ordering"
      tablename: imdb_principals
    -
      comment: "names in internet movie database (IMDb)"
      filename: name.basics.tsv.gz
      primary_key: nconst
      tablename: imdb_ratings
